graph LR
 hawq::test::CompentConfig::parseNode -->  hawq::test::CompentConfig::parseNodes
 hawq::test::MagmaConfig::MagmaConfig -->  hawq::test::TpcdsWorkloadBase::TpcdsWorkloadBase
 hawq::test::ConfigMap::parseConfig -->  hawq::test::ConfigMap::parseConfig
 hawq::test::ConfigMap::parseConfig -->  hawq::test::YamlProcessor::getConfigMap
 dblisp::ValType::asString -->  hawq::test::QueryGen::setVConf
 hawq::test::QueryGen::setVConf -->  hawq::test::QueryGen::init
 hawq::test::OushuDBConfig::__initParameter -->  hawq::test::OushuDBConfig::OushuDBConfig
 hawq::test::SQLUtility::getTestRootPath -->  hawq::test::SQLUtility::SQLUtility
 hawq::test::SQLUtility::getTestRootPath -->  hawq::test::TpcdsWorkloadBase::TpcdsWorkloadBase
 hawq::test::SQLUtility::splitFilePath -->  hawq::test::SQLUtility::getTestRootPath
 dblisp::RecTree::RecTree -->  dblisp::DbLispParser::lispToRecMap
 dblisp::KeyType::KeyType -->  dblisp::RecTree::RecTree
 hawq::test::TpcdsWorkload::initDatabase -->  hawq::test::TpcdsWorkload::init
 hawq::test::QueryGen::init -->  hawq::test::QueryGen::QueryGen
 hawq::test::SQLUtility::getSchemaSpace -->  hawq::test::SQLUtility::setSchemaName
 hawq::test::CompentConfig::parseNodes -->  hawq::test::CompentConfig::CompentConfig
 hawq::test::SQLUtility::getTestName -->  hawq::test::SQLUtility::SQLUtility
 hawq::test::SQLUtility::getDbSpace -->  hawq::test::SQLUtility::getSchemaSpace
 hawq::test::SQLUtility::getDbSpace -->  hawq::test::SQLUtility::SQLUtility
 hawq::test::PSQLQueryResult::getData -->  hawq::test::SQLUtility::getDbSpace
 hawq::test::MagmaConfig::parseVscList -->  hawq::test::MagmaConfig::MagmaConfig
 dblisp::RecTree::pushValue -->  dblisp::DbLispParser::wordToRecMap
 hawq::test::VSCConfig::VSCConfig -->  hawq::test::MagmaConfig::parseVscList
 hawq::test::TpcdsWorkload::prepareData -->  hawq::test::TpcdsWorkload::executeWorkloadFormat
 logtree::LogTree::printStart -->  logtree::LogTree::pushLog
 hawq::test::OushuDBConfig::OushuDBConfig -->  hawq::test::TpcdsWorkloadBase::TpcdsWorkloadBase
 hawq::test::TpcdsWorkload::executeWorkloadNewQE -->  hawq::test::TpcdsWorkload::executeWorkloadFormat
 hawq::test::YamlProcessor::getConfigMap -->  hawq::test::CompentConfig::CompentConfig
 hawq::test::PSQL::PSQL -->  hawq::test::SQLUtility::setConnList
 hawq::test::PSQL::PSQL -->  hawq::test::OushuDBConfig::OushuDBConfig
 registerNewExecutorTest -->  registerNewExecutorTest
 hawq::test::SQLUtility::setConnList -->  hawq::test::SQLUtility::SQLUtility
 hawq::test::TpcdsWorkload::executeWorkloadScale -->  hawq::test::TpcdsWorkload::executeWorkloadRound
 hawq::test::QueryGen::QueryGen -->  hawq::test::TpcdsWorkloadBase::TpcdsWorkloadBase
 hawq::test::TpcdsWorkload::executeWorkloadFormat -->  hawq::test::TpcdsWorkload::executeWorkloadScale
 hawq::test::TpcdsWorkload::executeWorkloadRound -->  hawq::test::TpcdsWorkload::executeWorkloadImple
 hawq::test::ResultStore::initResultStore -->  hawq::test::TpcdsWorkload::init
 hawq::test::VCConfig::VCConfig -->  hawq::test::OushuDBConfig::parseVcList
 hawq::test::SQLUtility::executeSql -->  hawq::test::SQLUtility::setCurrentVCluster
 hawq::test::OushuDBConfig::getVCProperty -->  hawq::test::TpcdsWorkloadBase::setConfigLisp
 hawq::test::split -->  hawq::test::SQLUtility::SQLUtility
 dblisp::RecTree::valueVector -->  hawq::test::TpcdsWorkloadBase::setConfigLisp
 dblisp::DbLispParser::wordToRecMap -->  dblisp::DbLispParser::lispToRecMap
 hawq::test::PSQL::runSQLCommand -->  hawq::test::SQLUtility::executeSql
 dblisp::RecTree::createValue -->  dblisp::RecTree::pushValue
 hawq::test::CompentConfig::CompentConfig -->  hawq::test::MagmaConfig::MagmaConfig
 hawq::test::CompentConfig::CompentConfig -->  hawq::test::OushuDBConfig::OushuDBConfig
 dblisp::RecTree::moveValToVec -->  dblisp::RecTree::pushValue
 dblisp::RecTree::moveValToVec -->  dblisp::RecTree::valueVector
 hawq::test::TpcdsWorkload::executeWorkloadImple -->  hawq::test::TpcdsWorkload::executeWorkload
 hawq::test::PSQL::getQueryResult -->  hawq::test::OushuDBConfig::getGucValue
 hawq::test::PSQL::getQueryResult -->  hawq::test::OushuDBConfig::getVCProperty
 hawq::test::PSQL::getQueryResult -->  hawq::test::SQLUtility::getDbSpace
 hawq::test::TpcdsWorkload::TpcdsWorkload -->  hawq::test::TestTPCDS::executeTpcds
 TestExtParser_TestFormatOption_Test::AddToRegistry -->  __cxx_global_var_init.19
 hawq::test::TpcdsWorkloadBase::TpcdsWorkloadBase -->  hawq::test::TpcdsWorkload::TpcdsWorkload
 hawq::test::XmlConfig::XmlConfig -->  hawq::test::ResultStore::initResultStore
 hawq::test::SQLUtility::setCurrentVCluster -->  hawq::test::SQLUtility::SQLUtility
 hawq::test::SQLUtility::initFormat -->  hawq::test::SQLUtility::SQLUtility
 hawq::test::TpcdsWorkloadBase::setConfigLisp -->  hawq::test::TpcdsWorkloadBase::parseConfigLisp
 dblisp::DbLispParser::lispToRecMap -->  hawq::test::TpcdsWorkloadBase::parseConfigLisp
 dblisp::DbLispParser::lispToRecMap -->  hawq::test::TpcdsWorkloadBase::setConfigLisp
 dblisp::DbLispParser::lispToRecMap -->  dblisp::DbLispParser::lispToRecMap
 hawq::test::TpcdsWorkload::executeWorkload -->  hawq::test::TestTPCDS::executeTpcds
 hawq::test::XmlConfig::parse -->  hawq::test::XmlConfig::XmlConfig
 TestORCOption_TestORCMultiKv_Test::AddToRegistry -->  __cxx_global_var_init.58
 dblisp::ValType::ValType -->  dblisp::RecTree::createValue
 TestHIVEOrcToHive_TestOrcToHive_Test::AddToRegistry -->  __cxx_global_var_init.42
 hawq::test::TpcdsWorkloadBase::parseConfigLisp -->  hawq::test::TpcdsWorkload::init
 hawq::test::OushuDBConfig::parseVcList -->  hawq::test::OushuDBConfig::OushuDBConfig
 TestExtHdfs_TestReadableExternalTable_Test::AddToRegistry -->  __cxx_global_var_init.9
 TestHIVEHiveToOrc_TestHiveToOrc_Test::AddToRegistry -->  __cxx_global_var_init.92
 TestDispatcherFault_TestMaintainParameterized_Test::AddToRegistry -->  __cxx_global_var_init.47
 hawq::test::SQLUtility::SQLUtility -->  hawq::test::SQLUtility::SQLUtility
 hawq::test::SQLUtility::SQLUtility -->  hawq::test::TpcdsWorkloadBase::TpcdsWorkloadBase
 hawq::test::SQLUtility::SQLUtility -->  hawq::test::QueryGen::QueryGen
 hawq::test::TpcdsWorkload::init -->  hawq::test::TpcdsWorkload::executeWorkloadImple
 hawq::test::SQLUtility::setSchemaName -->  hawq::test::TpcdsWorkload::initDatabase
 hawq::test::PSQLQueryResult::savePGResult -->  hawq::test::PSQL::getQueryResult
 dblisp::KeyType::createPointer -->  dblisp::KeyType::KeyType
 hawq::test::TpcdsWorkload::createExternalTables -->  hawq::test::TpcdsWorkload::prepareData

